<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ6NWKxx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ6NWKxx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ6NWKxx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ6NWKxx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZ6NWKxx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Z6NWKxx',
    'container.build_id' => 'b2da0f81',
    'container.build_time' => 1627866434,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ6NWKxx');
