<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLFWRIgD\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLFWRIgD/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLFWRIgD.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLFWRIgD\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLFWRIgD\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LFWRIgD',
    'container.build_id' => '4e844ef1',
    'container.build_time' => 1627959074,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLFWRIgD');
